# Generated by Django 2.1 on 2019-01-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('muncipality_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
