# Generated by Django 2.1 on 2019-01-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0002_municipalitygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalitygroup',
            old_name='muncipality_name',
            new_name='municipality_name',
        ),
    ]
