# Generated by Django 2.0.6 on 2018-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0002_municipalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('study_location', models.CharField(max_length=100)),
                ('population_band', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Municipalities',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='municipalities',
        ),
        migrations.AddField(
            model_name='enduser',
            name='municipality_name',
            field=models.CharField(default='Toronto', max_length=100),
            preserve_default=False,
        ),
    ]
