# Generated by Django 2.1 on 2019-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0003_auto_20190106_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitygroup',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
