# Generated by Django 2.1 on 2019-12-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0004_municipalitygroup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitydata',
            name='agriculture_and_reforestation',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='municipalitydata',
            name='landfill',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
