# Generated by Django 2.1 on 2018-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0004_municipalitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='municipality_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='userid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='population_band',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='study_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ambulance',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='apartment_units_at_least_2_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='apartment_units_less_than_2_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='assistance_to_the_aged',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='average_residential_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='bridges_and_culverts',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='building_construction_per_capita_value',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='building_construction_value',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='building_permit_fee',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='bungalow',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='cemeteries',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='child_care',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='comm_and_ind',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial_10000_m3_2_inch',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial_office',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial_parking',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='commercial_shopping',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='conservation_authority',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='consumption_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='cultural',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='debt_to_reserve_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_comm_office',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_comm_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_comm_shopping',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_commercial_park_vac',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_ind_large',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_ind_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_multi_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='education_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='emergency_measures',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='estimated_average_household_income',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='executive',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='farmlands',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='financial_position_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='fire',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='forests',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='general_assistance',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='general_government',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='hotel',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_100000_m3_4_inch',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_30000_m3_3_inch',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_500000_m3_6_inch',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_large',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_standard',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='industrial_vacant',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='land_area_km2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='levy_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='library',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='lower_tier_levy',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='lower_tier_levy_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='motel',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='multi_res_high_rise',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='multi_res_walk_up',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='multi_residential',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='multiples_dwelling_1_or_2_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='multiples_dwelling_3_plus_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_comm_office',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_comm_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_comm_shopping',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_commercial_park_vac',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_ind_large',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_ind_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_multi_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='municipal_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='museums',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='net_financial_liabilities_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='new_multi_residential',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='non_residential_commercial_per_sq_ft',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='non_residential_industrial_per_sq_ft',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='office',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='parking',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='parks',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='pipelines',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='planning',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='poa',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='population_bands',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='population_density_per_km2',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='population_increase_percent',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='property_taxes_percent_household_income',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='public_health',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='rates_coverage_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='rec_fac_golf',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='rec_facilities_other',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='recreation_programs',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='recycling',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='region_county_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='residential',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='residential_200_m3_5_8_inch',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='roads_paved',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='shopping',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='single_detached_dwellings_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='social_housing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='storm',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='study_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_asset',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_debt_charges_percent_osr',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_debt_int_percent_osr',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_debt_outstanding_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_discretionary_reserves_percent_own_source_revenues',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_reserves_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tax_reserves_percent_taxation',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='taxes_receivable_percent_taxes_levied',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='tier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_comm_office',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_comm_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_comm_shopping',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_commercial_park_vac',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_debt_outstanding_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_ind_large',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_ind_residual',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_multi_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_municipal_burden_percent_household_income',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_municipal_tax_burden',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_net_levy_upper_and_lower_tiers',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_resid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_unweighted_assessment',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='total_weighted_assessment',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='traffic',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='transit',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='two_storey',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='unweighted_assessment_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='upper_tier_levy',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='upper_tier_levy_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='waste_collection',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='waste_disposal',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='water_asset_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='water_debt_interest_coverage',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='water_net_lin_liab',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='water_res_as_percent_acum_amort',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='water_res_as_percent_osr',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='weighted_assessment_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='weighted_median_dwelling_value',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='winter_roads',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='winter_sidewalks',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ww_asset_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ww_debt_interest_coverage',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ww_net_lin_liab',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ww_res_percent_acum_amort',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='ww_res_percent_osr',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
