# Generated by Django 2.1 on 2018-09-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmaapp', '0005_auto_20180822_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipalitydata',
            old_name='consumption_ratio',
            new_name='est_avg_household_income',
        ),
        migrations.RenameField(
            model_name='municipalitydata',
            old_name='tax_asset',
            new_name='multi_residential_tax_ratio',
        ),
        migrations.RemoveField(
            model_name='municipalitydata',
            name='id',
        ),
        migrations.AddField(
            model_name='municipalitydata',
            name='residential_water_sewer_costs',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='municipalitydata',
            name='tax_asset_consumption_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='municipalitydata',
            name='yearPlusName',
            field=models.CharField(default='2018Default', max_length=104, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='name',
            field=models.CharField(default='default municipality name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipalitydata',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
