api_server_url <- 'http://localhost:8000/bmaapp/'
login_endpoint <- 'login'
municipalities_endpoint <- 'municipalities'
all_municipalities_endpoint <- 'all_municipalities'
data_endpoint <- 'data'
columns_by_years_endpoint <- 'data_subset_by_years'

# Only Municipality column is non-numeric
non_numeric_cols_count <- 1
export_filename <-"bmaExport.xls"

# Errors
kErrorTitleFailedToLoadData = 'Failed to Load from Excel File'

get_recent_years <- function(selected_year) {
  year <- as.numeric(selected_year) 
  (year-3):(year-1)
}

get_population_years <- function(selected_year) {
  year <- as.numeric(selected_year)

  # Census is every 5 years. Start from 2006
  start_year = 2006
  if (year <= start_year) {
    population_years <- list(year)
  }
  else {
    population_years <- seq(from = start_year, to = year, by = 5)
  }

  # selected year must always be the last element. add only if it's not already there
  if (tail(population_years, n = 1) != year) {
    population_years <- append(population_years, year)
  }
  population_years
}

current_year <- as.integer(format(Sys.Date(), "%Y"))
default_selected_year <- 2018
oldest_year <- 2002L
years_all_options <- oldest_year: current_year
recent_years <- get_recent_years(default_selected_year)
population_years <- get_population_years(default_selected_year)

SUB_TAB_POPULATION <- "Population"
SUB_TAB_POPULATION_BY_YEAR <- "Population by Year"
SUB_TAB_DENSITY_LAND_AREA <- "Density and Land Area"
SUB_TAB_ASSESSMENT_INFO <- "Assessment Information"
SUB_TAB_ASSESSMENT_COMPOSITION <- "Assessment Composition"
SUB_TAB_BUILDING_PERMIT_ACTIVITY_BY_YEAR <- "Building Permit Activity"
SUB_TAB_TOTAL_LEYY <- "Total Levy"
SUB_TAB_UPPER_TIER_LEVY <- "Upper Tier Levy"
SUB_TAB_LOWER_TIER_LEVY <- "Lower Tier Levy"
SUB_TAB_TAX_ASSET_CONSUMPTION_RATIO <- "Tax Asset Consumption Ratio"
SUB_TAB_FINANCIAL_POSITION_PER_CAPITA <- "Financial Position per Capita"
SUB_TAB_TAX_DIS_RES_PERCENT_OSR <- "Tax Dis Res as Percent OSR"
SUB_TAB_TAX_RESERVES_PERCENT_TAXATION <- "Tax Reserves as Percent of Taxation"
SUB_TAB_TAX_RES_PER_CAPITA <- "Tax Res per Capita"
SUB_TAB_TAX_DEBT_INT_PERCENT_OSR <- "Tax Debt Int Percent OSR"
SUB_TAB_TAX_DEBT_CHARGES_PERCENT_OSR <- "Tax Debt Charges as Percent OSR"
SUB_TAB_TOTAL_TAX_DEBT_OUT_PER_CAPITA <- "Total Debt Out per Capita"
SUB_TAB_TAX_DEBT_OUT_PER_CAPITA <- "Tax Debt Out per Capita"
SUB_TAB_DEBT_TO_RESERVE_RATIO <- "Debt to Reserve Ratio"
SUB_TAB_TAX_RECEIVABLE_PERCENT_TAX <- "Tax Receivable as Percent Tax"
SUB_TAB_RATES_COVERAGE_RATIO <- "Rates Coverage Ratio"
SUB_TAB_NET_FIN_LIAB_RATIO <- "Net Fin Liab Ratio"
SUB_TAB_DEVELOPMENT_CHARGES <- "Development Charges"
SUB_TAB_BUILDING_PERMIT_FEES <- "Building Permit Fees"
SUB_TAB_TAX_RATIOS <- "Tax Ratios"
SUB_TAB_OPTIONAL_CLASS <- "Optional Class"
SUB_TAB_TOTAL_TAX_RATES <- "Total Tax Rates"
SUB_TAB_MUNICIPAL_TAX_RATES <- "Municipal Tax Rates"
SUB_TAB_EDUCATIONL_TAX_RATES <- "Education Tax Rates"
SUB_TAB_RESIDENTIAL <- "Residential"
SUB_TAB_MULTI_RESIDENTIAL <- "Multi-Residential"
SUB_TAB_COMMERCIAL <- "Commercial"
SUB_TAB_INDUSTRIAL <- "Industrial"
SUB_TAB_WATER_AND_SEWER_COSTS <- "Water and Sewer Costs"
SUB_TAB_WATER_ASSET_CONSUMPTION <- "Water Asset Consumption"
SUB_TAB_WASTE_WATER_ASSET_CONSUMPTION <- "Wastewater Asset Consumption"
SUB_TAB_WATER_RES_PERCENT_OSR <- "Water Res as Percent OSR"
SUB_TAB_WASTE_WATER_RES_PERCENT_OSR <- "Wastewater Res as Percent OSR"
SUB_TAB_WATER_RES_PERCENT_ACUM_AMORT <- "Water Res as Percent Acum Amort"
SUB_TAB_WASTE_WATER_RES_PERCENT_ACUM_AMORT <- "Wastewater Res as Percent Acum Amort"
SUB_TAB_WATER_DEBT_INT_COVER <- "Water Debt Int Cover"
SUB_TAB_WASTE_WATER_DEBT_INT_COVER <- "Wastewater Debt Int Cover"
SUB_TAB_WATER_NET_FIN_LIAB <- "Water Net Fin Liab"
SUB_TAB_WASTE_WATER_NET_FIN_LIAB <- "Wastewater Net Fin Liab"
SUB_TAB_AVG_HOUSEHOLD_INCOME <- "Average Household Income"
SUB_TAB_AVG_VALUE_DWELLING <- "Average Value of Dwelling"
SUB_TAB_COMBINED_COSTS <- "Combined costs"
SUB_TAB_TAXES_PERCENT_INCOME <- "Taxes as a Percent of Income"
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_FIRE = 'Fire Services'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ROADS_PAVED = 'Roadways - Paved'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_BRIDGES_CULVERTS = 'Roadways - Bridges and Culverts'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRAFFIC = 'Roadways - Traffic Control'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_ROADS = 'Winter Control - Roads'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_SIDEWALKS = 'Winter Control - Sidewalks'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRANSIT = 'Transit Services'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKING = 'Parking'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_COLLECTION = 'Waste Collection'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_DISPOSAL = 'Waste Disposal'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_STORM = 'Storm Sewer'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECYCLING = 'Recycling'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PUBLIC_HEALTH = 'Public Health'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_EMERGENCY_MEASURES = 'Emergency Measures'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_ASSISTANCE = 'General Assistance'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ASSISTANCE_AGED = 'Assistance to the Aged'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_POA = 'POA'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CHILD_CARE = 'Child Care'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_SOCIAL_HOUSING = 'Social Housing'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKS = 'Parks'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECREATION_PROGRAMS = 'Rec Programs'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FAC_GOLF = 'Rec Facilities Golf'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FACILITIES_OTHER = 'Rec Facilities Other'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_LIBRARY = 'Library'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_MUSEUMS = 'Museums'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CULTURAL = 'Cultural Services'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PLANNING = 'Planning'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_COMM_IND = 'Comm and Ind'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_GOVERNMENT = 'General Government'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CONSERVATION_AUTHORITY = 'Conservation Authority'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_AMBULANCE = 'Ambulance'
SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CEMETERIES = 'Cemeteries'

COLUMN_NAME_MUNICIPALITY = 'Municipality'
COLUMN_NAME_POPULATION = 'Population'
COLUMN_NAME_POPULATION_DENSITY = 'Population Density per sq. km.'
COLUMN_NAME_POPULATION_INCREASE = 'Population Increase'
COLUMN_NAME_BUILDING_CONSTRUCTION_PER_CAPITA = 'Building Construction Value per Capita'
COLUMN_NAME_ESTIMATED_AVG_HOUSEHOLD_INCOME = 'Estimated Average Household Income'
COLUMN_NAME_WEIGHTED_MEDIAN_VAL_DWELLING = 'Weighted Median Value of Dwelling'
COLUMN_NAME_UNWEIGHTED_ASSESSMENT_PER_CAPITA = 'Unweighted Assessment per Capita'
COLUMN_NAME_WEIGHTED_ASSESSMENT_PER_CAPITA = 'Weighted Assessment per Capita'
COLUMN_NAME_LAND_AREA = 'Land Area km2'
COLUMN_NAME_TOTAL_UNWEIGHTED_ASSESSMENT = 'Total Unweighted Assessment'
COLUMN_NAME_TOTAL_WEIGHTED_ASSESSMENT = 'Total Weighted Assessment'
COLUMN_NAME_RESIDENTIAL = 'Residential'
COLUMN_NAME_MULTI_RESIDENTIAL = 'Multi-Residential'
COLUMN_NAME_COMMERCIAL = 'Commercial'
COLUMN_NAME_INDUSTRIAL = 'Industrial'
COLUMN_NAME_PIPELINES = 'Pipelines'
COLUMN_NAME_FARMLANDS = 'Farmlands'
COLUMN_NAME_FORESTS = 'Forests'
COLUMN_NAME_BUILDING_CONSTRUCTION_VALUE = 'Building Construction Value ($000)'
COLUMN_NAME_BUILDING_CONSTRUCTION_PER_CAPITA_WITH_YEAR_PREFIX = 'per Capita'
COLUMN_NAME_TOTAL_NET_LEVY = 'Total Net Levy (Upper and Lower Tiers)'
COLUMN_NAME_LEVY_PER_CAPITA = 'Levy per Capita'
COLUMN_NAME_UPPER_TIER_LEVY = 'Upper Tier Levy'
COLUMN_NAME_UPPER_TIER_LEVY_PER_CAPITA = 'Upper Tier Levy per Capita'
COLUMN_NAME_LOWER_TIER_LEVY = 'Lower Tier Levy'
COLUMN_NAME_LOWER_TIER_LEVY_PER_CAPITA = 'Lower Tier Levy per Capita'
COLUMN_NAME_TAX_ASSET_CONSUMPTION_RATIO = 'Tax Asset Consumption Ratio'
COLUMN_NAME_FINANCIAL_POSITION_PER_CAPITA = 'Financial Position per Capita'
COLUMN_NAME_TAX_DISCRETIONARY_RESERVES_PERCENT_SOURCE_REVENUES = 'Tax Discretionary Reserves as a % of Own Source Revenues'
COLUMN_NAME_TAX_RESERVES_PERCENT_TAXATION = 'Tax Reserves as a % of Taxation'
COLUMN_NAME_TAX_RESERVE_PER_CAPITA = 'Tax Reserves / Capita'
COLUMN_NAME_TAX_DEBT_INT_PERCENT_OSR = 'Tax Debt Int as % OSR'
COLUMN_NAME_TAXR_DEBT_CHARGES_PERCENT_OSR = 'Tax Debt Charges as % OSR'
COLUMN_NAME_TOTAL_DEBT_OUTSTANDING_PER_CAPITA = 'Total Debt Outstanding / Capita'
COLUMN_NAME_TAX_DEBT_OUTSTANDING_PER_CAPITA = 'Tax Debt Outstanding / Capita'
COLUMN_NAME_DEBT_TO_RESERVE_RATIO = 'Debt to Reserve Ratio'
COLUMN_NAME_TAXES_RECEIVABLE_PERCENT_TAXES_LEVIED = 'Taxes Receivable as a % of Taxes Levied'
COLUMN_NAME_RATES_COVERAGE_RATIO = 'Rates Coverage Ratio'
COLUMN_NAME_NET_FINANCIAL_LIABILITIES_RATIO = 'Net Financial Liabilities Ratio'
COLUMN_NAME_SINGLE_DETACHED_DWELLINGS_PER_UNIT = 'Single Detached Dwellings per unit'
COLUMN_NAME_MULTIPLES_DWELLING__3_OR_MORE = 'Multiples Dwelling 3+ per unit'
COLUMN_NAME_MULTIPLES_DWELLING_1_OR_2 = 'Multiples Dwelling 1&2 per unit'
COLUMN_NAME_APARTMENT_UNITS_2_OR_MORE = 'Apartment units >=2 per unit'
COLUMN_NAME_APARTMENT_UNITS_LESS_THAN_2 = 'Apartment units < 2 per unit'
COLUMN_NAME_NON_RESIDENTIAL_COMMERCIAL_PER_SQFT = 'Non Residential Commercial per sq. ft.'
COLUMN_NAME_NON_RESIDENTIAL_INDUSTRIAL_PER_SQFT = 'Non Residential Industrial per sq. ft.'
COLUMN_NAME_BUILDING_PERMIT_FEE = 'Building Permit Fee'
COLUMN_NAME_TAX_RATIOS_MULTI_RESIDENTIAL = 'Multi-Residential Tax Ratio'
COLUMN_NAME_TAX_RATIOS_COMMERCIAL_RESIDUAL = 'Commercial (Residual)'
COLUMN_NAME_TAX_RATIOS_INDUSTRIAL_RESIDUAL = 'Industrial (Residual)'
COLUMN_NAME_NEW_MULTI_RESIDENTIAL = 'New Multi-Residential'
COLUMN_NAME_COMMERCIAL_OFFICE = 'Commercial Office'
COLUMN_NAME_COMMERCIAL_SHOPPING = 'Commercial Shopping'
COLUMN_NAME_COMMERCIAL_PARKING = 'Commercial Parking'
COLUMN_NAME_INDUSTRIAL_LARGE = 'Industrial Large'
COLUMN_NAME_TOTAL_RESID = 'Total Resid.'
COLUMN_NAME_TOTAL_MULTI_RESID = 'Total Multi Resid.'
COLUMN_NAME_TOTAL_COMMERCIAL_RESIDUAL = 'Total Comm.  Residual'
COLUMN_NAME_TOTAL_COMMERCIAL_OFFICE = 'Total Comm.  Office'
COLUMN_NAME_TOTAL_COMMERCIAL_PARK_VAC = 'Total Commercial Park/Vac'
COLUMN_NAME_TOTAL_COMMERCIAL_SHOPPING = 'Total Comm.  Shopping'
COLUMN_NAME_TOTAL_INDUSTRIAL_RESIDUAL = 'Total Ind. Residual'
COLUMN_NAME_TOTAL_INDUSTRIAL_LARGE = 'Total Ind. Large'
COLUMN_NAME_MUNICIPAL_RESID = 'Municipal Resid.'
COLUMN_NAME_MUNICIPAL_MULTI_RESID = 'Municipal Multi Resid.'
COLUMN_NAME_MUNICIPAL_COMM_RESIDUAL = 'Municipal Comm.  Residual'
COLUMN_NAME_MUNICIPAL_COMM_OFFICE = 'Municipal Comm.  Office'
COLUMN_NAME_MUNICIPAL_COMMERCIAL_PARK_VAC = 'Municipal Commercial Park/Vac'
COLUMN_NAME_MUNICIPAL_COMM_SHOPPING = 'Municipal Comm.  Shopping'
COLUMN_NAME_MUNICIPAL_IND_RESIDUAL = 'Municipal Ind. Residual'
COLUMN_NAME_MUNICIPAL_IND_LARGE = 'Municipal Ind. Large'
COLUMN_NAME_EDUCATION_RESID = 'Education Resid.'
COLUMN_NAME_EDUCATION_MULTI_RESID = 'Education Multi Resid.'
COLUMN_NAME_EDUCATION_COMM_RESIDUAL = 'Education Comm.  Residual'
COLUMN_NAME_EDUCATION_COMM_OFFICE = 'Education Comm.  Office'
COLUMN_NAME_EDUCATION_COMMERCIAL_PARK_VAC = 'Education Commercial Park/Vac'
COLUMN_NAME_EDUCATION_COMM_SHOPPING = 'Education Comm.  Shopping'
COLUMN_NAME_EDUCATION_IND_RESIDUAL = 'Education Ind. Residual'
COLUMN_NAME_EDUCATION_IND_LARGE = 'Education Ind. Large'
COLUMN_NAME_BUNGALOW = 'Bungalow'
COLUMN_NAME_2_STOREY = '2 Storey'
COLUMN_NAME_EXECUTIVE = 'Executive'
COLUMN_NAME_MULTI_RES_WALK_UP = 'Multi-Res Walk up'
COLUMN_NAME_MULTI_RES_HIGH_RISE = 'Multi-Res High Rise'
COLUMN_NAME_TAX_SHOPPING = 'Shopping'
COLUMN_NAME_TAX_HOTEL = 'Hotel'
COLUMN_NAME_TAX_MOTEL = 'Motel'
COLUMN_NAME_TAX_OFFICE = 'Office'
COLUMN_NAME_TAX_IND_STANDARD = 'Industrial Standard'
COLUMN_NAME_TAX_IND_LARGE = 'Industrial Large'
COLUMN_NAME_TAX_IND_VACANT = 'Industrial Vacant'
COLUMN_NAME_RESIDENTIAL_200_M3 = 'Residential 200 m3 5/8"'
COLUMN_NAME_COMMERCIAL_10K_M3 = 'Commercial  10,000 m3 2"'
COLUMN_NAME_INDUSTRIAL_30K_M3 = 'Industrial  30,000 m3 3"'
COLUMN_NAME_INDUSTRIAL_100K_M3 = 'Industrial  100,000 m3 4"'
COLUMN_NAME_INDUSTRIAL_500K_M3 = 'Industrial  500,000 m3 6"'
COLUMN_NAME_WATER_ASSET_CONSUMPTION = 'Water Asset Consumption'
COLUMN_NAME_WW_ASSET_CONSUMPTION = 'WW Asset Consumption'
COLUMN_NAME_WATER_RES_PERCENT_OSR = 'Water Res As % OSR'
COLUMN_NAME_WW_RES_PERCENT_OSR = 'WW Res As % OSR'
COLUMN_NAME_WATER_RES_PERCENT_ACUM_AMORT = 'Water Res as % Acum Amort'
COLUMN_NAME_WW_RES_PERCENT_ACUM_AMORT = 'WW Res as % Acum Amort'
COLUMN_NAME_WATER_DEBT_INTEREST_COVERAGE = 'Water Debt Interest Coverage'
COLUMN_NAME_WW_DEBT_INTEREST_COVERAGE = 'WW Debt Interest Coverage'
COLUMN_NAME_WATER_NET_LIN_LIAB = 'Water Net Lin Liab'
COLUMN_NAME_WW_NET_LIN_LIAB = 'WW Net Lin Liab'
COLUMN_NAME_EST_AVG_HOUSEHOLD_INCOME = 'Est. Avg. Household Income'
COLUMN_NAME_RESIDENTIAL_WATER_SEWER_COSTS = 'Residential - Water and Sewer Costs'
COLUMN_NAME_AVG_RESIDENTIAL_TAXES = 'Average Residential Taxes'
COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN = 'Total Municipal Tax Burden'
COLUMN_NAME_PROPERTY_TAXES_PERCENT_HOUSEHOLD_INCOME = 'Property Taxes as a % of Household Income'
COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN_PERCENT_HOUSEHOLD_INCOME = 'Total Municipal Burden as a % of Household Income'
COLUMN_NAME_FIRE = 'Fire'
COLUMN_NAME_ROADS_PAVED = 'Roads Paved'
COLUMN_NAME_BRIDGES_CULVERTS = 'Bridges and Culverts'
COLUMN_NAME_TRAFFIC = 'Traffic'
COLUMN_NAME_WINTER_ROADS = 'Winter Roads'
COLUMN_NAME_WINTER_SIDEWALKS = 'Winter Sidewalks'
COLUMN_NAME_TRANSIT = 'Transit'
COLUMN_NAME_PARKING = 'Parking'
COLUMN_NAME_WASTE_COLLECTION = 'Waste Collection'
COLUMN_NAME_WASTE_DISPOSAL = 'Waste Disposal'
COLUMN_NAME_STORM = 'Storm'
COLUMN_NAME_RECYCLING = 'Recycling'
COLUMN_NAME_PUBLIC_HEALTH = 'Public Health'
COLUMN_NAME_EMERGENCY_MEASURES = 'Emergency Measures'
COLUMN_NAME_GENERAL_ASSISTANCE = 'General Assistance'
COLUMN_NAME_ASSISTANCE_AGED = 'Assistance to the Aged'
COLUMN_NAME_POA = 'POA'
COLUMN_NAME_CHILD_CARE = 'Child Care'
COLUMN_NAME_SOCIAL_HOUSING = 'Social Housing'
COLUMN_NAME_PARKS = 'Parks'
COLUMN_NAME_RECREATION_PROGRAMS = 'Recreation Programs'
COLUMN_NAME_REC_FAC_GOLF = 'Rec Fac Golf'
COLUMN_NAME_REC_FACILITIES_OTHER = 'Rec Facilities Other'
COLUMN_NAME_LIBRARY = 'Library'
COLUMN_NAME_MUSEUMS = 'Museums'
COLUMN_NAME_CULTURAL = 'Cultural'
COLUMN_NAME_PLANNING = 'Planning'
COLUMN_NAME_COMM_IND = 'Comm & Ind.'
COLUMN_NAME_GENERAL_GOVERNMENT = 'General Government'
COLUMN_NAME_CONSERVATION_AUTHORITY = 'Conservation Authority'
COLUMN_NAME_AMBULANCE = 'Ambulance'
COLUMN_NAME_CEMETERIES = 'Cemeteries'

SHEET_NET_EXPENDITURES_PER_CAPITA <- "Net Expenditures per Capita"

menu_sub_tabs_text <- list(
  "Socio Economic Indicators" = list(SUB_TAB_POPULATION, SUB_TAB_POPULATION_BY_YEAR, SUB_TAB_DENSITY_LAND_AREA, SUB_TAB_ASSESSMENT_INFO, 
                                     SUB_TAB_ASSESSMENT_COMPOSITION, SUB_TAB_BUILDING_PERMIT_ACTIVITY_BY_YEAR),
  
  "Municipal Financial Indicators" = list(SUB_TAB_TOTAL_LEYY, SUB_TAB_UPPER_TIER_LEVY, SUB_TAB_LOWER_TIER_LEVY, SUB_TAB_TAX_ASSET_CONSUMPTION_RATIO, SUB_TAB_FINANCIAL_POSITION_PER_CAPITA,
       SUB_TAB_TAX_DIS_RES_PERCENT_OSR, SUB_TAB_TAX_RESERVES_PERCENT_TAXATION, SUB_TAB_TAX_RES_PER_CAPITA, SUB_TAB_TAX_DEBT_INT_PERCENT_OSR,
       SUB_TAB_TAX_DEBT_CHARGES_PERCENT_OSR, SUB_TAB_TOTAL_TAX_DEBT_OUT_PER_CAPITA, SUB_TAB_TAX_DEBT_OUT_PER_CAPITA, SUB_TAB_DEBT_TO_RESERVE_RATIO,
       SUB_TAB_TAX_RECEIVABLE_PERCENT_TAX, SUB_TAB_RATES_COVERAGE_RATIO, SUB_TAB_NET_FIN_LIAB_RATIO),
  
  "Select User Fee Information" = list(SUB_TAB_DEVELOPMENT_CHARGES, SUB_TAB_BUILDING_PERMIT_FEES),
  
  "Tax Policies" = list(SUB_TAB_TAX_RATIOS, SUB_TAB_OPTIONAL_CLASS),
  
  "Comparison of Relative Taxes" = list(SUB_TAB_TOTAL_TAX_RATES, SUB_TAB_MUNICIPAL_TAX_RATES, SUB_TAB_EDUCATIONL_TAX_RATES, SUB_TAB_RESIDENTIAL, SUB_TAB_MULTI_RESIDENTIAL,
       SUB_TAB_COMMERCIAL, SUB_TAB_INDUSTRIAL),
  
  "Comparison of Water & Sewer Costs" = list(SUB_TAB_WATER_AND_SEWER_COSTS, SUB_TAB_WATER_ASSET_CONSUMPTION, SUB_TAB_WASTE_WATER_ASSET_CONSUMPTION, SUB_TAB_WATER_RES_PERCENT_OSR,
       SUB_TAB_WASTE_WATER_RES_PERCENT_OSR, SUB_TAB_WATER_RES_PERCENT_ACUM_AMORT, SUB_TAB_WASTE_WATER_RES_PERCENT_ACUM_AMORT, SUB_TAB_WATER_DEBT_INT_COVER,
       SUB_TAB_WASTE_WATER_DEBT_INT_COVER, SUB_TAB_WATER_NET_FIN_LIAB, SUB_TAB_WASTE_WATER_NET_FIN_LIAB),
  
  "Taxes as a % of Income" = list(SUB_TAB_AVG_HOUSEHOLD_INCOME, SUB_TAB_AVG_VALUE_DWELLING, SUB_TAB_COMBINED_COSTS, SUB_TAB_TAXES_PERCENT_INCOME)
)

menu_sub_tabs_text[[SHEET_NET_EXPENDITURES_PER_CAPITA]] = list(
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_FIRE, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ROADS_PAVED, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_BRIDGES_CULVERTS, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRAFFIC, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_ROADS, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_SIDEWALKS, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRANSIT, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKING, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_COLLECTION, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_DISPOSAL, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_STORM, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECYCLING, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PUBLIC_HEALTH, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_EMERGENCY_MEASURES, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_ASSISTANCE,
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ASSISTANCE_AGED, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_POA, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CHILD_CARE, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_SOCIAL_HOUSING, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKS, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECREATION_PROGRAMS, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FAC_GOLF, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FACILITIES_OTHER, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_LIBRARY, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_MUSEUMS, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CULTURAL, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PLANNING, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_COMM_IND, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_GOVERNMENT, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CONSERVATION_AUTHORITY, 
    SUB_TAB_NET_EXPENDITURES_PER_CAPITA_AMBULANCE, SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CEMETERIES)

data_set_names <- list.flatten(menu_sub_tabs_text)
data_set_exclusions <- list(SUB_TAB_POPULATION_BY_YEAR)
data_set_percent_character_exclusions <-list(SUB_TAB_TAX_DIS_RES_PERCENT_OSR, SUB_TAB_TAX_RESERVES_PERCENT_TAXATION, SUB_TAB_TAX_DEBT_INT_PERCENT_OSR, 
                                            SUB_TAB_TAX_DEBT_CHARGES_PERCENT_OSR, SUB_TAB_TAX_RECEIVABLE_PERCENT_TAX, SUB_TAB_WATER_RES_PERCENT_OSR, 
                                            SUB_TAB_WASTE_WATER_RES_PERCENT_OSR, SUB_TAB_WATER_RES_PERCENT_ACUM_AMORT, SUB_TAB_WASTE_WATER_RES_PERCENT_ACUM_AMORT, 
                                            SUB_TAB_TAXES_PERCENT_INCOME)
data_set_percent_character_additions <- lapply(data_set_percent_character_exclusions, function(str) {
  sub("Percent", "%", str)
})
data_set_and_character_exclusions <- list(SUB_TAB_WATER_AND_SEWER_COSTS)
data_set_and_character_additions <- lapply(data_set_and_character_exclusions, function(str) {
  sub(" and ", "&", str)
})


data_set_names <- unique(setdiff(
  list.flatten(list.append(data_set_names, data_set_percent_character_additions, data_set_and_character_additions, SHEET_NET_EXPENDITURES_PER_CAPITA)), 
  list.flatten(list.append(data_set_exclusions, data_set_percent_character_exclusions, data_set_and_character_exclusions, menu_sub_tabs_text[[SHEET_NET_EXPENDITURES_PER_CAPITA]])))
)

column_names_per_sub_tab_selection <- list()
column_names_per_sub_tab_selection[[SUB_TAB_POPULATION]] = list(
  COLUMN_NAME_POPULATION_DENSITY, COLUMN_NAME_POPULATION_INCREASE, COLUMN_NAME_WEIGHTED_MEDIAN_VAL_DWELLING, COLUMN_NAME_UNWEIGHTED_ASSESSMENT_PER_CAPITA, 
  COLUMN_NAME_WEIGHTED_ASSESSMENT_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_DENSITY_LAND_AREA]] = list(COLUMN_NAME_POPULATION_DENSITY, COLUMN_NAME_LAND_AREA)
column_names_per_sub_tab_selection[[SUB_TAB_ASSESSMENT_INFO]] = list(
  COLUMN_NAME_TOTAL_UNWEIGHTED_ASSESSMENT, COLUMN_NAME_TOTAL_WEIGHTED_ASSESSMENT, COLUMN_NAME_UNWEIGHTED_ASSESSMENT_PER_CAPITA, 
  COLUMN_NAME_WEIGHTED_ASSESSMENT_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_ASSESSMENT_COMPOSITION]] = list(
  COLUMN_NAME_RESIDENTIAL, COLUMN_NAME_MULTI_RESIDENTIAL, COLUMN_NAME_COMMERCIAL, COLUMN_NAME_INDUSTRIAL, COLUMN_NAME_PIPELINES, COLUMN_NAME_FARMLANDS, 
  COLUMN_NAME_FORESTS)
column_names_per_sub_tab_selection[[SUB_TAB_TOTAL_LEYY]] = list(COLUMN_NAME_TOTAL_NET_LEVY, COLUMN_NAME_LEVY_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_UPPER_TIER_LEVY]] = list(COLUMN_NAME_UPPER_TIER_LEVY, COLUMN_NAME_UPPER_TIER_LEVY_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_LOWER_TIER_LEVY]] = list(COLUMN_NAME_LOWER_TIER_LEVY, COLUMN_NAME_LOWER_TIER_LEVY_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_ASSET_CONSUMPTION_RATIO]] = list(COLUMN_NAME_TAX_ASSET_CONSUMPTION_RATIO)
column_names_per_sub_tab_selection[[SUB_TAB_FINANCIAL_POSITION_PER_CAPITA]] = list(COLUMN_NAME_FINANCIAL_POSITION_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_DIS_RES_PERCENT_OSR]] = list(COLUMN_NAME_TAX_DISCRETIONARY_RESERVES_PERCENT_SOURCE_REVENUES)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_RESERVES_PERCENT_TAXATION]] = list(COLUMN_NAME_TAX_RESERVES_PERCENT_TAXATION)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_RES_PER_CAPITA]] = list(COLUMN_NAME_TAX_RESERVE_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_DEBT_INT_PERCENT_OSR]] = list(COLUMN_NAME_TAX_DEBT_INT_PERCENT_OSR)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_DEBT_CHARGES_PERCENT_OSR]] = list(COLUMN_NAME_TAXR_DEBT_CHARGES_PERCENT_OSR)
column_names_per_sub_tab_selection[[SUB_TAB_TOTAL_TAX_DEBT_OUT_PER_CAPITA]] = list(COLUMN_NAME_TOTAL_DEBT_OUTSTANDING_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_DEBT_OUT_PER_CAPITA]] = list(COLUMN_NAME_TAX_DEBT_OUTSTANDING_PER_CAPITA)
column_names_per_sub_tab_selection[[SUB_TAB_DEBT_TO_RESERVE_RATIO]] = list(COLUMN_NAME_DEBT_TO_RESERVE_RATIO)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_RECEIVABLE_PERCENT_TAX]] = list(COLUMN_NAME_TAXES_RECEIVABLE_PERCENT_TAXES_LEVIED)
column_names_per_sub_tab_selection[[SUB_TAB_RATES_COVERAGE_RATIO]] = list(COLUMN_NAME_RATES_COVERAGE_RATIO)
column_names_per_sub_tab_selection[[SUB_TAB_NET_FIN_LIAB_RATIO]] = list(COLUMN_NAME_NET_FINANCIAL_LIABILITIES_RATIO)
column_names_per_sub_tab_selection[[SUB_TAB_DEVELOPMENT_CHARGES]] = list(
  COLUMN_NAME_SINGLE_DETACHED_DWELLINGS_PER_UNIT, COLUMN_NAME_MULTIPLES_DWELLING__3_OR_MORE, COLUMN_NAME_MULTIPLES_DWELLING_1_OR_2, 
  COLUMN_NAME_APARTMENT_UNITS_2_OR_MORE, COLUMN_NAME_APARTMENT_UNITS_LESS_THAN_2, COLUMN_NAME_NON_RESIDENTIAL_COMMERCIAL_PER_SQFT, 
  COLUMN_NAME_NON_RESIDENTIAL_INDUSTRIAL_PER_SQFT)
column_names_per_sub_tab_selection[[SUB_TAB_BUILDING_PERMIT_FEES]] = list(COLUMN_NAME_BUILDING_PERMIT_FEE)
column_names_per_sub_tab_selection[[SUB_TAB_TAX_RATIOS]] = list(
  COLUMN_NAME_TAX_RATIOS_MULTI_RESIDENTIAL, COLUMN_NAME_TAX_RATIOS_COMMERCIAL_RESIDUAL, COLUMN_NAME_TAX_RATIOS_INDUSTRIAL_RESIDUAL)
column_names_per_sub_tab_selection[[SUB_TAB_OPTIONAL_CLASS]] = list(
  COLUMN_NAME_NEW_MULTI_RESIDENTIAL, COLUMN_NAME_COMMERCIAL_OFFICE, COLUMN_NAME_COMMERCIAL_SHOPPING, COLUMN_NAME_COMMERCIAL_PARKING, COLUMN_NAME_INDUSTRIAL_LARGE)
column_names_per_sub_tab_selection[[SUB_TAB_TOTAL_TAX_RATES]] = list(
  COLUMN_NAME_TOTAL_RESID, COLUMN_NAME_TOTAL_MULTI_RESID, COLUMN_NAME_TOTAL_COMMERCIAL_RESIDUAL, COLUMN_NAME_TOTAL_COMMERCIAL_OFFICE, 
  COLUMN_NAME_TOTAL_COMMERCIAL_PARK_VAC, COLUMN_NAME_TOTAL_COMMERCIAL_SHOPPING, COLUMN_NAME_TOTAL_INDUSTRIAL_RESIDUAL, COLUMN_NAME_TOTAL_INDUSTRIAL_LARGE)
column_names_per_sub_tab_selection[[SUB_TAB_MUNICIPAL_TAX_RATES]] = list(
  COLUMN_NAME_MUNICIPAL_RESID, COLUMN_NAME_MUNICIPAL_MULTI_RESID, COLUMN_NAME_MUNICIPAL_COMM_RESIDUAL, COLUMN_NAME_MUNICIPAL_COMM_OFFICE, 
  COLUMN_NAME_MUNICIPAL_COMMERCIAL_PARK_VAC, COLUMN_NAME_MUNICIPAL_COMM_SHOPPING, COLUMN_NAME_MUNICIPAL_IND_RESIDUAL, COLUMN_NAME_MUNICIPAL_IND_LARGE)
column_names_per_sub_tab_selection[[SUB_TAB_EDUCATIONL_TAX_RATES]] = list(
  COLUMN_NAME_EDUCATION_RESID, COLUMN_NAME_EDUCATION_MULTI_RESID, COLUMN_NAME_EDUCATION_COMM_RESIDUAL, COLUMN_NAME_EDUCATION_COMM_OFFICE, 
  COLUMN_NAME_EDUCATION_COMMERCIAL_PARK_VAC, COLUMN_NAME_EDUCATION_COMM_SHOPPING, COLUMN_NAME_EDUCATION_IND_RESIDUAL, COLUMN_NAME_EDUCATION_IND_LARGE)
column_names_per_sub_tab_selection[[SUB_TAB_RESIDENTIAL]] = list(COLUMN_NAME_BUNGALOW, COLUMN_NAME_2_STOREY, COLUMN_NAME_EXECUTIVE)
column_names_per_sub_tab_selection[[SUB_TAB_MULTI_RESIDENTIAL]] = list(COLUMN_NAME_MULTI_RES_WALK_UP, COLUMN_NAME_MULTI_RES_HIGH_RISE)
column_names_per_sub_tab_selection[[SUB_TAB_COMMERCIAL]] = list(COLUMN_NAME_TAX_SHOPPING, COLUMN_NAME_TAX_HOTEL, COLUMN_NAME_TAX_MOTEL, COLUMN_NAME_TAX_OFFICE)
column_names_per_sub_tab_selection[[SUB_TAB_INDUSTRIAL]] = list(COLUMN_NAME_TAX_IND_STANDARD, COLUMN_NAME_TAX_IND_LARGE, COLUMN_NAME_TAX_IND_VACANT)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_AND_SEWER_COSTS]] = list(
  COLUMN_NAME_RESIDENTIAL_200_M3, COLUMN_NAME_COMMERCIAL_10K_M3, COLUMN_NAME_INDUSTRIAL_30K_M3, COLUMN_NAME_INDUSTRIAL_100K_M3, COLUMN_NAME_INDUSTRIAL_500K_M3)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_ASSET_CONSUMPTION]] = list(COLUMN_NAME_WATER_ASSET_CONSUMPTION)
column_names_per_sub_tab_selection[[SUB_TAB_WASTE_WATER_ASSET_CONSUMPTION]] = list(COLUMN_NAME_WW_ASSET_CONSUMPTION)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_RES_PERCENT_OSR]] = list(COLUMN_NAME_WATER_RES_PERCENT_OSR)
column_names_per_sub_tab_selection[[SUB_TAB_WASTE_WATER_RES_PERCENT_OSR]] = list(COLUMN_NAME_WW_RES_PERCENT_OSR)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_RES_PERCENT_ACUM_AMORT]] = list(COLUMN_NAME_WATER_RES_PERCENT_ACUM_AMORT)
column_names_per_sub_tab_selection[[SUB_TAB_WASTE_WATER_RES_PERCENT_ACUM_AMORT]] = list(COLUMN_NAME_WW_RES_PERCENT_ACUM_AMORT)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_DEBT_INT_COVER]] = list(COLUMN_NAME_WATER_DEBT_INTEREST_COVERAGE)
column_names_per_sub_tab_selection[[SUB_TAB_WASTE_WATER_DEBT_INT_COVER]] = list(COLUMN_NAME_WW_DEBT_INTEREST_COVERAGE)
column_names_per_sub_tab_selection[[SUB_TAB_WATER_NET_FIN_LIAB]] = list(COLUMN_NAME_WATER_NET_LIN_LIAB)
column_names_per_sub_tab_selection[[SUB_TAB_WASTE_WATER_NET_FIN_LIAB]] = list(COLUMN_NAME_WW_NET_LIN_LIAB)
column_names_per_sub_tab_selection[[SUB_TAB_AVG_HOUSEHOLD_INCOME]] = list(COLUMN_NAME_EST_AVG_HOUSEHOLD_INCOME)
column_names_per_sub_tab_selection[[SUB_TAB_AVG_VALUE_DWELLING]] = list(COLUMN_NAME_WEIGHTED_MEDIAN_VAL_DWELLING)
column_names_per_sub_tab_selection[[SUB_TAB_COMBINED_COSTS]] = list(COLUMN_NAME_RESIDENTIAL_WATER_SEWER_COSTS, COLUMN_NAME_AVG_RESIDENTIAL_TAXES, COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN)
column_names_per_sub_tab_selection[[SUB_TAB_TAXES_PERCENT_INCOME]] = list(
  COLUMN_NAME_AVG_RESIDENTIAL_TAXES, COLUMN_NAME_PROPERTY_TAXES_PERCENT_HOUSEHOLD_INCOME, COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN, 
  COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN_PERCENT_HOUSEHOLD_INCOME)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_FIRE]] = list(COLUMN_NAME_FIRE) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ROADS_PAVED]] = list(COLUMN_NAME_ROADS_PAVED) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_BRIDGES_CULVERTS]] = list(COLUMN_NAME_BRIDGES_CULVERTS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRAFFIC]] = list(COLUMN_NAME_TRAFFIC)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_ROADS]] = list(COLUMN_NAME_WINTER_ROADS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WINTER_SIDEWALKS]] = list(COLUMN_NAME_WINTER_SIDEWALKS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_TRANSIT]] = list(COLUMN_NAME_TRANSIT) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKING]] = list(COLUMN_NAME_PARKING)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_COLLECTION]] = list(COLUMN_NAME_WASTE_COLLECTION) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_WASTE_DISPOSAL]] = list(COLUMN_NAME_WASTE_DISPOSAL) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_STORM]] = list(COLUMN_NAME_STORM) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECYCLING]] = list(COLUMN_NAME_RECYCLING)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PUBLIC_HEALTH]] = list(COLUMN_NAME_PUBLIC_HEALTH) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_EMERGENCY_MEASURES]] = list(COLUMN_NAME_EMERGENCY_MEASURES) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_ASSISTANCE]] = list(COLUMN_NAME_GENERAL_ASSISTANCE)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_ASSISTANCE_AGED]] = list(COLUMN_NAME_ASSISTANCE_AGED) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_POA]] = list(COLUMN_NAME_POA) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CHILD_CARE]] = list(COLUMN_NAME_CHILD_CARE) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_SOCIAL_HOUSING]] = list(COLUMN_NAME_SOCIAL_HOUSING)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PARKS]] = list(COLUMN_NAME_PARKS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_RECREATION_PROGRAMS]] = list(COLUMN_NAME_RECREATION_PROGRAMS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FAC_GOLF]] = list(COLUMN_NAME_REC_FAC_GOLF) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_REC_FACILITIES_OTHER]] = list(COLUMN_NAME_REC_FACILITIES_OTHER)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_LIBRARY]] = list(COLUMN_NAME_LIBRARY) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_MUSEUMS]] = list(COLUMN_NAME_MUSEUMS) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CULTURAL]] = list(COLUMN_NAME_CULTURAL) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_PLANNING]] = list(COLUMN_NAME_PLANNING) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_COMM_IND]] = list(COLUMN_NAME_COMM_IND)
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_GENERAL_GOVERNMENT]] = list(COLUMN_NAME_GENERAL_GOVERNMENT) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CONSERVATION_AUTHORITY]] = list(COLUMN_NAME_CONSERVATION_AUTHORITY) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_AMBULANCE]] = list(COLUMN_NAME_AMBULANCE) 
column_names_per_sub_tab_selection[[SUB_TAB_NET_EXPENDITURES_PER_CAPITA_CEMETERIES]] = list(COLUMN_NAME_CEMETERIES)

ALL_COLUMN_NAMES_LIST <- unique(append(list(COLUMN_NAME_MUNICIPALITY),
                                       list.flatten(column_names_per_sub_tab_selection)))

FORMAT_SETTINGS_CURRENCY_DEFAULT = list("SYMBOL" = "$", "SEPARATOR" = ",", "DECIMALS" = 0)
FORMAT_SETTINGS_CURRENCY_2_DECIMALS = list("SYMBOL" = "$", "SEPARATOR" = ",", "DECIMALS" = 2)
FORMAT_SETTINGS_COUNTER = list("SYMBOL" = "", "SEPARATOR" = ",", "DECIMALS" = 0)
FORMAT_SETTINGS_PERCENT_1_DECIMAL = list("SYMBOL" = "%", "SEPARATOR" = ",", "DECIMALS" = 1)
FORMAT_SETTINGS_PERCENT_2_DECIMALS = list("SYMBOL" = "%", "SEPARATOR" = ",", "DECIMALS" = 2)
FORMAT_SETTINGS_PERCENT_4_DECIMALS = list("SYMBOL" = "%", "SEPARATOR" = ",", "DECIMALS" = 4)
FORMAT_SETTINGS_PERCENT_6_DECIMALS = list("SYMBOL" = "%", "SEPARATOR" = ",", "DECIMALS" = 6)

AS_IS_DISPLAY_COLUMNS = list(COLUMN_NAME_MUNICIPALITY)

COLUMNS_COUNTER = c(COLUMN_NAME_POPULATION, COLUMN_NAME_POPULATION_DENSITY, COLUMN_NAME_LAND_AREA)

COLUMNS_PERCENT_1_DECIMAL = c(COLUMN_NAME_WATER_NET_LIN_LIAB, COLUMN_NAME_WW_NET_LIN_LIAB)

COLUMNS_PERCENT_2_DECIMALS = c(COLUMN_NAME_POPULATION_INCREASE, COLUMN_NAME_RESIDENTIAL, COLUMN_NAME_MULTI_RESIDENTIAL, COLUMN_NAME_COMMERCIAL, 
                               COLUMN_NAME_INDUSTRIAL, COLUMN_NAME_PIPELINES, COLUMN_NAME_FARMLANDS, COLUMN_NAME_FORESTS, COLUMN_NAME_TAX_ASSET_CONSUMPTION_RATIO, 
                               COLUMN_NAME_TAX_DISCRETIONARY_RESERVES_PERCENT_SOURCE_REVENUES, COLUMN_NAME_TAX_RESERVES_PERCENT_TAXATION, 
                               COLUMN_NAME_TAX_DEBT_INT_PERCENT_OSR, COLUMN_NAME_TAXR_DEBT_CHARGES_PERCENT_OSR, COLUMN_NAME_DEBT_TO_RESERVE_RATIO, 
                               COLUMN_NAME_TAXES_RECEIVABLE_PERCENT_TAXES_LEVIED, COLUMN_NAME_RATES_COVERAGE_RATIO, COLUMN_NAME_NET_FINANCIAL_LIABILITIES_RATIO, 
                               COLUMN_NAME_WATER_ASSET_CONSUMPTION, COLUMN_NAME_WW_ASSET_CONSUMPTION, COLUMN_NAME_WATER_RES_PERCENT_OSR, COLUMN_NAME_WW_RES_PERCENT_OSR, 
                               COLUMN_NAME_WATER_RES_PERCENT_ACUM_AMORT, COLUMN_NAME_WW_RES_PERCENT_ACUM_AMORT, COLUMN_NAME_WATER_DEBT_INTEREST_COVERAGE, 
                               COLUMN_NAME_WW_DEBT_INTEREST_COVERAGE, COLUMN_NAME_PROPERTY_TAXES_PERCENT_HOUSEHOLD_INCOME, 
                               COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN_PERCENT_HOUSEHOLD_INCOME)

COLUMNS_PERCENT_4_DECIMALS = c(COLUMN_NAME_TAX_RATIOS_MULTI_RESIDENTIAL, COLUMN_NAME_TAX_RATIOS_COMMERCIAL_RESIDUAL, COLUMN_NAME_TAX_RATIOS_INDUSTRIAL_RESIDUAL, 
                               COLUMN_NAME_NEW_MULTI_RESIDENTIAL, COLUMN_NAME_COMMERCIAL_OFFICE, COLUMN_NAME_COMMERCIAL_SHOPPING, COLUMN_NAME_COMMERCIAL_PARKING, 
                               COLUMN_NAME_INDUSTRIAL_LARGE)

COLUMNS_PERCENT_6_DECIMALS = c(COLUMN_NAME_TOTAL_RESID, COLUMN_NAME_TOTAL_MULTI_RESID, COLUMN_NAME_TOTAL_COMMERCIAL_RESIDUAL, COLUMN_NAME_TOTAL_COMMERCIAL_OFFICE, 
                               COLUMN_NAME_TOTAL_COMMERCIAL_PARK_VAC, COLUMN_NAME_TOTAL_COMMERCIAL_SHOPPING, COLUMN_NAME_TOTAL_INDUSTRIAL_RESIDUAL, COLUMN_NAME_TOTAL_INDUSTRIAL_LARGE, 
                               COLUMN_NAME_MUNICIPAL_RESID, COLUMN_NAME_MUNICIPAL_MULTI_RESID, COLUMN_NAME_MUNICIPAL_COMM_RESIDUAL, COLUMN_NAME_MUNICIPAL_COMM_OFFICE, 
                               COLUMN_NAME_MUNICIPAL_COMMERCIAL_PARK_VAC, COLUMN_NAME_MUNICIPAL_COMM_SHOPPING, COLUMN_NAME_MUNICIPAL_IND_RESIDUAL, 
                               COLUMN_NAME_MUNICIPAL_IND_LARGE, COLUMN_NAME_EDUCATION_RESID, COLUMN_NAME_EDUCATION_MULTI_RESID, COLUMN_NAME_EDUCATION_COMM_RESIDUAL, 
                               COLUMN_NAME_EDUCATION_COMM_OFFICE, COLUMN_NAME_EDUCATION_COMMERCIAL_PARK_VAC, COLUMN_NAME_EDUCATION_COMM_SHOPPING,
                               COLUMN_NAME_EDUCATION_IND_RESIDUAL, COLUMN_NAME_EDUCATION_IND_LARGE)

COLUMNS_CURRENCY_2_DECIMALS = c(COLUMN_NAME_NON_RESIDENTIAL_COMMERCIAL_PER_SQFT, COLUMN_NAME_NON_RESIDENTIAL_INDUSTRIAL_PER_SQFT, COLUMN_NAME_TAX_SHOPPING, 
                                COLUMN_NAME_TAX_OFFICE, COLUMN_NAME_TAX_IND_STANDARD, COLUMN_NAME_TAX_IND_LARGE)

COLUMNS_CURRENCY_0_DECIMALS = c(COLUMN_NAME_BUILDING_CONSTRUCTION_PER_CAPITA, COLUMN_NAME_ESTIMATED_AVG_HOUSEHOLD_INCOME, COLUMN_NAME_WEIGHTED_MEDIAN_VAL_DWELLING, 
                                COLUMN_NAME_UNWEIGHTED_ASSESSMENT_PER_CAPITA, COLUMN_NAME_WEIGHTED_ASSESSMENT_PER_CAPITA, COLUMN_NAME_TOTAL_UNWEIGHTED_ASSESSMENT, 
                                COLUMN_NAME_TOTAL_WEIGHTED_ASSESSMENT, COLUMN_NAME_BUILDING_CONSTRUCTION_VALUE, COLUMN_NAME_BUILDING_CONSTRUCTION_PER_CAPITA_WITH_YEAR_PREFIX,
                                COLUMN_NAME_TOTAL_NET_LEVY, COLUMN_NAME_LEVY_PER_CAPITA, COLUMN_NAME_UPPER_TIER_LEVY, COLUMN_NAME_UPPER_TIER_LEVY_PER_CAPITA, 
                                COLUMN_NAME_LOWER_TIER_LEVY, COLUMN_NAME_LOWER_TIER_LEVY_PER_CAPITA, COLUMN_NAME_FINANCIAL_POSITION_PER_CAPITA, 
                                COLUMN_NAME_TAX_RESERVE_PER_CAPITA, COLUMN_NAME_TOTAL_DEBT_OUTSTANDING_PER_CAPITA, COLUMN_NAME_TAX_DEBT_OUTSTANDING_PER_CAPITA, 
                                COLUMN_NAME_SINGLE_DETACHED_DWELLINGS_PER_UNIT, COLUMN_NAME_MULTIPLES_DWELLING__3_OR_MORE, COLUMN_NAME_MULTIPLES_DWELLING_1_OR_2, 
                                COLUMN_NAME_APARTMENT_UNITS_2_OR_MORE, COLUMN_NAME_APARTMENT_UNITS_LESS_THAN_2, COLUMN_NAME_BUILDING_PERMIT_FEE, COLUMN_NAME_BUNGALOW, 
                                COLUMN_NAME_2_STOREY, COLUMN_NAME_EXECUTIVE, COLUMN_NAME_MULTI_RES_WALK_UP, COLUMN_NAME_MULTI_RES_HIGH_RISE, COLUMN_NAME_TAX_HOTEL, 
                                COLUMN_NAME_TAX_MOTEL, COLUMN_NAME_TAX_IND_VACANT, COLUMN_NAME_RESIDENTIAL_200_M3, COLUMN_NAME_COMMERCIAL_10K_M3, 
                                COLUMN_NAME_INDUSTRIAL_30K_M3, COLUMN_NAME_INDUSTRIAL_100K_M3, COLUMN_NAME_INDUSTRIAL_500K_M3, COLUMN_NAME_EST_AVG_HOUSEHOLD_INCOME, 
                                COLUMN_NAME_RESIDENTIAL_WATER_SEWER_COSTS, COLUMN_NAME_AVG_RESIDENTIAL_TAXES, COLUMN_NAME_TOTAL_MUNICIPAL_BURDEN, COLUMN_NAME_FIRE, 
                                COLUMN_NAME_ROADS_PAVED, COLUMN_NAME_BRIDGES_CULVERTS, COLUMN_NAME_TRAFFIC, COLUMN_NAME_WINTER_ROADS, COLUMN_NAME_WINTER_SIDEWALKS, 
                                COLUMN_NAME_TRANSIT, COLUMN_NAME_PARKING, COLUMN_NAME_WASTE_COLLECTION, COLUMN_NAME_WASTE_DISPOSAL, COLUMN_NAME_STORM, COLUMN_NAME_RECYCLING, 
                                COLUMN_NAME_PUBLIC_HEALTH, COLUMN_NAME_EMERGENCY_MEASURES, COLUMN_NAME_GENERAL_ASSISTANCE, COLUMN_NAME_ASSISTANCE_AGED, COLUMN_NAME_POA, 
                                COLUMN_NAME_CHILD_CARE, COLUMN_NAME_SOCIAL_HOUSING, COLUMN_NAME_PARKS, COLUMN_NAME_RECREATION_PROGRAMS, COLUMN_NAME_REC_FAC_GOLF, 
                                COLUMN_NAME_REC_FACILITIES_OTHER, COLUMN_NAME_LIBRARY, COLUMN_NAME_MUSEUMS, COLUMN_NAME_CULTURAL, COLUMN_NAME_PLANNING, COLUMN_NAME_COMM_IND, 
                                COLUMN_NAME_GENERAL_GOVERNMENT, COLUMN_NAME_CONSERVATION_AUTHORITY, COLUMN_NAME_AMBULANCE, COLUMN_NAME_CEMETERIES)