from django.db import models

# create your models here.
default_decimal_places = 2
default_max_digits_year = 4
default_max_digits = 13
default_max_string_length = 100

class EndUser(models.Model):
    userid = models.CharField(max_length=default_max_string_length, null=True)
    municipality_name =  models.CharField(max_length=default_max_string_length, null=True)

class Municipality(models.Model):
    name = models.CharField(max_length=default_max_string_length, null=True)
    study_location = models.CharField(max_length=default_max_string_length, null=True)
    population_band = models.CharField(max_length=default_max_string_length, null=True)

class MunicipalityData(models.Model):
    # id???
    name = models.CharField(max_length=default_max_string_length, null=True)
    region_county_district = models.CharField(max_length=default_max_string_length, null=True)
    study_location = models.CharField(max_length=default_max_string_length, null=True)
    tier = models.CharField(max_length=default_max_string_length, null=True)
    population_bands = models.CharField(max_length=default_max_string_length, null=True)
    land_area_km2 = models.CharField(max_length=default_max_string_length, null=True)
    year = models.IntegerField(null=True)
    population = models.IntegerField(null=True)
    population_density_per_km2 = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    population_increase_percent = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    building_construction_value = models.DecimalField(max_digits=default_max_digits , decimal_places=default_decimal_places, null=True)
    building_construction_per_capita_value = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    estimated_average_household_income = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    weighted_median_dwelling_value = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_unweighted_assessment = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_weighted_assessment = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    unweighted_assessment_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    weighted_assessment_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    single_detached_dwellings_per_unit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    multiples_dwelling_3_plus_per_unit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    multiples_dwelling_1_or_2_per_unit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    apartment_units_at_least_2_per_unit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    apartment_units_less_than_2_per_unit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    non_residential_commercial_per_sq_ft = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    non_residential_industrial_per_sq_ft = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    building_permit_fee = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    residential_200_m3_5_8_inch = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial_10000_m3_2_inch = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_30000_m3_3_inch = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_100000_m3_4_inch = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_500000_m3_6_inch = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    water_asset_consumption = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ww_asset_consumption = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    water_res_as_percent_osr = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    water_res_as_percent_acum_amort = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ww_res_percent_osr = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ww_res_percent_acum_amort = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    water_debt_interest_coverage = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ww_debt_interest_coverage = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    water_net_lin_liab = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ww_net_lin_liab = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    average_residential_taxes = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    property_taxes_percent_household_income = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_municipal_tax_burden = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_municipal_burden_percent_household_income = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    residential = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    multi_residential = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    pipelines = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    farmlands = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    forests = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    fire = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    roads_paved = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    bridges_and_culverts = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    traffic = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    winter_roads = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    winter_sidewalks = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    transit = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    parking = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    waste_collection = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    waste_disposal = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    storm = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    recycling = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    public_health = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    emergency_measures = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    general_assistance = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    assistance_to_the_aged = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    poa = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    child_care = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    social_housing = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    parks = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    recreation_programs = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    rec_fac_golf = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    rec_facilities_other = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    library = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    museums = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    cultural = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    planning = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    comm_and_ind = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    general_government = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    conservation_authority = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    ambulance = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    cemeteries = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    multi_residential = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    new_multi_residential = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial_office = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial_shopping = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    commercial_parking = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_large = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    total_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_multi_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_comm_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_comm_office = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_commercial_park_vac = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_comm_shopping = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_ind_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_ind_large = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    education_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_multi_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_comm_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_comm_office = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_commercial_park_vac = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_comm_shopping = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_ind_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    education_ind_large = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    municipal_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_multi_resid = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_comm_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_comm_office = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_commercial_park_vac = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_comm_shopping = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_ind_residual = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    municipal_ind_large = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    bungalow = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    two_storey = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    executive = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    multi_res_walk_up = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    multi_res_high_rise = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    shopping = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    hotel = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    motel = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    office = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_standard = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_large = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    industrial_vacant = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    total_net_levy_upper_and_lower_tiers = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    levy_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    lower_tier_levy = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    lower_tier_levy_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    upper_tier_levy = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    upper_tier_levy_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    tax_asset = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    consumption_ratio = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    financial_position_per_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_discretionary_reserves_percent_own_source_revenues = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_reserves_percent_taxation = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_reserves_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_debt_int_percent_osr = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_debt_charges_percent_osr = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    total_debt_outstanding_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    tax_debt_outstanding_capita = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    debt_to_reserve_ratio = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    taxes_receivable_percent_taxes_levied = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    rates_coverage_ratio = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)
    net_financial_liabilities_ratio = models.DecimalField(max_digits=default_max_digits, decimal_places=default_decimal_places, null=True)

    def load(self, dict):
        # id???
        self.name = dict.get('name')
        self.region_county_district = dict.get('region_county_district')
        self.study_location = dict.get('study_location')
        self.tier = dict.get('tier')
        self.population_bands = dict.get('population_bands')
        self.land_area_km2 = dict.get('land_area_km2')
        self.year = dict.get('year')
        self.population = dict.get('population')
        self.population_density_per_km2 = dict.get('population_density_per_km2')
        self.population_increase_percent = dict.get('population_increase_percent')
        self.building_construction_value = dict.get('building_construction_value')
        self.building_construction_per_capita_value = dict.get('building_construction_per_capita_value')
        self.estimated_average_household_income = dict.get('estimated_average_household_income')
        self.weighted_median_dwelling_value = dict.get('weighted_median_dwelling_value')
        self.total_unweighted_assessment = dict.get('total_unweighted_assessment')
        self.total_weighted_assessment = dict.get('total_weighted_assessment')
        self.unweighted_assessment_per_capita = dict.get('unweighted_assessment_per_capita')
        self.weighted_assessment_per_capita = dict.get('weighted_assessment_per_capita')
        self.single_detached_dwellings_per_unit = dict.get('single_detached_dwellings_per_unit')
        self.multiples_dwelling_3_plus_per_unit = dict.get('multiples_dwelling_3_plus_per_unit')
        self.multiples_dwelling_1_or_2_per_unit = dict.get('multiples_dwelling_1_or_2_per_unit')
        self.apartment_units_at_least_2_per_unit = dict.get('apartment_units_at_least_2_per_unit')
        self.apartment_units_less_than_2_per_unit = dict.get('apartment_units_less_than_2_per_unit')
        self.non_residential_commercial_per_sq_ft = dict.get('non_residential_commercial_per_sq_ft')
        self.non_residential_industrial_per_sq_ft = dict.get('non_residential_industrial_per_sq_ft')
        self.building_permit_fee = dict.get('building_permit_fee')
        self.residential_200_m3_5_8_inch = dict.get('residential_200_m3_5_8_inch')
        self.commercial_10000_m3_2_inch = dict.get('commercial_10000_m3_2_inch')
        self.industrial_30000_m3_3_inch = dict.get('industrial_30000_m3_3_inch')
        self.industrial_100000_m3_4_inch = dict.get('industrial_100000_m3_4_inch')
        self.industrial_500000_m3_6_inch = dict.get('industrial_500000_m3_6_inch')
        self.water_asset_consumption = dict.get('water_asset_consumption')
        self.ww_asset_consumption = dict.get('ww_asset_consumption')
        self.water_res_as_percent_osr = dict.get('water_res_as_percent_osr')
        self.water_res_as_percent_acum_amort = dict.get('water_res_as_percent_acum_amort')
        self.ww_res_percent_osr = dict.get('ww_res_percent_osr')
        self.ww_res_percent_acum_amort = dict.get('ww_res_percent_acum_amort')
        self.water_debt_interest_coverage = dict.get('water_debt_interest_coverage')
        self.ww_debt_interest_coverage = dict.get('ww_debt_interest_coverage')
        self.water_net_lin_liab = dict.get('water_net_lin_liab')
        self.ww_net_lin_liab = dict.get('ww_net_lin_liab')
        self.average_residential_taxes = dict.get('average_residential_taxes')
        self.property_taxes_percent_household_income = dict.get('property_taxes_percent_household_income')
        self.total_municipal_tax_burden = dict.get('total_municipal_tax_burden')
        self.total_municipal_burden_percent_household_income = dict.get('total_municipal_burden_percent_household_income')
    
        self.residential = dict.get('residential')
        self.multi_residential = dict.get('multi_residential')
        self.commercial = dict.get('commercial')
        self.industrial = dict.get('industrial')
        self.pipelines = dict.get('pipelines')
        self.farmlands = dict.get('farmlands')
        self.forests = dict.get('forests')
        self.fire = dict.get('fire')
        self.roads_paved = dict.get('roads_paved')
        self.bridges_and_culverts = dict.get('bridges_and_culverts')
        self.traffic = dict.get('traffic')
        self.winter_roads = dict.get('winter_roads')
        self.winter_sidewalks = dict.get('winter_sidewalks')
        self.transit = dict.get('transit')
        self.parking = dict.get('parking')
        self.waste_collection = dict.get('waste_collection')
        self.waste_disposal = dict.get('waste_disposal')
        self.storm = dict.get('storm')
        self.recycling = dict.get('recycling')
        self.public_health = dict.get('public_health')
        self.emergency_measures = dict.get('emergency_measures')
        self.general_assistance = dict.get('general_assistance')
        self.assistance_to_the_aged = dict.get('assistance_to_the_aged')
        self.poa = dict.get('poa')
        self.child_care = dict.get('child_care')
        self.social_housing = dict.get('social_housing')
        self.parks = dict.get('parks')
        self.recreation_programs = dict.get('recreation_programs')
        self.rec_fac_golf = dict.get('rec_fac_golf')
        self.rec_facilities_other = dict.get('rec_facilities_other')
        self.library = dict.get('library')
        self.museums = dict.get('museums')
        self.cultural = dict.get('cultural')
        self.planning = dict.get('planning')
        self.comm_and_ind = dict.get('comm_and_ind')
        self.general_government = dict.get('general_government')
        self.conservation_authority = dict.get('conservation_authority')
        self.ambulance = dict.get('ambulance')
        self.cemeteries = dict.get('cemeteries')
    
        self.multi_residential = dict.get('multi_residential')
        self.commercial_residual = dict.get('commercial_residual')
        self.industrial_residual = dict.get('industrial_residual')
        self.new_multi_residential = dict.get('new_multi_residential')
        self.commercial_office = dict.get('commercial_office')
        self.commercial_shopping = dict.get('commercial_shopping')
        self.commercial_parking = dict.get('commercial_parking')
        self.industrial_large = dict.get('industrial_large')
    
        self.total_resid = dict.get('total_resid')
        self.total_multi_resid = dict.get('total_multi_resid')
        self.total_comm_residual = dict.get('total_comm_residual')
        self.total_comm_office = dict.get('total_comm_office')
        self.total_commercial_park_vac = dict.get('total_commercial_park_vac')
        self.total_comm_shopping = dict.get('total_comm_shopping')
        self.total_ind_residual = dict.get('total_ind_residual')
        self.total_ind_large = dict.get('total_ind_large')
    
        self.education_resid = dict.get('education_resid')
        self.education_multi_resid = dict.get('education_multi_resid')
        self.education_comm_residual = dict.get('education_comm_residual')
        self.education_comm_office = dict.get('education_comm_office')
        self.education_commercial_park_vac = dict.get('education_commercial_park_vac')
        self.education_comm_shopping = dict.get('education_comm_shopping')
        self.education_ind_residual = dict.get('education_ind_residual')
        self.education_ind_large = dict.get('education_ind_large')
    
        self.municipal_resid = dict.get('municipal_resid')
        self.municipal_multi_resid = dict.get('municipal_multi_resid')
        self.municipal_comm_residual = dict.get('municipal_comm_residual')
        self.municipal_comm_office = dict.get('municipal_comm_office')
        self.municipal_commercial_park_vac = dict.get('municipal_commercial_park_vac')
        self.municipal_comm_shopping = dict.get('municipal_comm_shopping')
        self.municipal_ind_residual = dict.get('municipal_ind_residual')
        self.municipal_ind_large = dict.get('municipal_ind_large')
    
        self.bungalow = dict.get('bungalow')
        self.two_storey = dict.get('two_storey')
        self.executive = dict.get('executive')
        self.multi_res_walk_up = dict.get('multi_res_walk_up')
        self.multi_res_high_rise = dict.get('multi_res_high_rise')
        self.shopping = dict.get('shopping')
        self.hotel = dict.get('hotel')
        self.motel = dict.get('motel')
        self.office = dict.get('office')
        self.industrial_standard = dict.get('industrial_standard')
        self.industrial_large = dict.get('industrial_large')
        self.industrial_vacant = dict.get('industrial_vacant')
    
        self.total_net_levy_upper_and_lower_tiers = dict.get('total_net_levy_upper_and_lower_tiers')
        self.levy_per_capita = dict.get('levy_per_capita')
        self.lower_tier_levy = dict.get('lower_tier_levy')
        self.lower_tier_levy_per_capita = dict.get('lower_tier_levy_per_capita')
        self.upper_tier_levy = dict.get('upper_tier_levy')
        self.upper_tier_levy_per_capita = dict.get('upper_tier_levy_per_capita')
    
        self.tax_asset = dict.get('tax_asset')
        self.consumption_ratio = dict.get('consumption_ratio')
        self.financial_position_per_capita = dict.get('financial_position_per_capita')
        self.tax_discretionary_reserves_percent_own_source_revenues = dict.get('tax_discretionary_reserves_percent_own_source_revenues')
        self.tax_reserves_percent_taxation = dict.get('tax_reserves_percent_taxation')
        self.tax_reserves_capita = dict.get('tax_reserves_capita')
        self.tax_debt_int_percent_osr = dict.get('tax_debt_int_percent_osr')
        self.tax_debt_charges_percent_osr = dict.get('tax_debt_charges_percent_osr')
        self.total_debt_outstanding_capita = dict.get('total_debt_outstanding_capita')
        self.tax_debt_outstanding_capita = dict.get('tax_debt_outstanding_capita')
        self.debt_to_reserve_ratio = dict.get('debt_to_reserve_ratio')
        self.taxes_receivable_percent_taxes_levied = dict.get('taxes_receivable_percent_taxes_levied')
        self.rates_coverage_ratio = dict.get('rates_coverage_ratio')
        self.net_financial_liabilities_ratio = dict.get('net_financial_liabilities_ratio')